server:
  port: 7083


spring:
  application:
    name: cloud-order-hystrix-payment
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:  jdbc:mysql://localhost:3306/springcloud?useUnicode=true&characterEncoding=utf-8&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 999520

#eureka相关
eureka:
  client:
    #表示是否将机子注册进eurekaServer
    register-with-eureka: false
    #是否从eurekaServer抓取已有的注册信息
    fetch-registry: true
    service-url:
      #defaultZone:  http://localhost:7001/eureka #单机版eureka配置
      defaultZone:  http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka       #eureka集群版配置

#设置feign客户端超时时间（openFeign默认支持ribbon）
ribbon:
  #值的是简历连接后从服务器读取到可用资源所用的时间
  ReadTimeout: 5000
  #值的是建立连接所用 短时间，适用于网络状态正常的情况下，两端连接所用的时间
  ConnectTimeout: 5000

# 用于服务降级 在注解@FeignClient中添加fallbackFactory属性值
feign:
  hystrix:
    enabled: true #在Feign中开启Hystrix
